### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [katschre/firehose_one#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by katschre** [comment]
Thanks Ken. I added the meta tag  <meta name="viewport" content="width=device-width, initial-scale=1"> and it now appears to be responsive on Mobile.

**Comment by katschre** [comment]
The meta tag I added :   <meta name="viewport" content="width=device-width, initial-scale=1">

**Comment by kenmazaika** [comment]
Looks perfect.  Thumbs up on getting it! :+1:
